### ISSUE TITLE
Separate the OpenGL utilities from the rendering

### ISSUE THREAD

**Issue by PPilmeyer** [leaf3d/leaf3d#1]
The renderer right now is responsible to hide the gl-call (allocating buffer, textures, ect) and the rendering itself which is also pretty tight to the classic 3D rendering with light/materials. Renderer should be cut in two part : a context object (L3DContext) and a more generic renderer. L3DContext could have one or more renderers which should coexist. Each renderer would be link to a "family" of shaders and the current renderer will be a specific renderer for classic 3D rendering.

Feel free to disagree. This suggestion matches my needs and I will understand if you don't want to.
The rest of the project looks very nice and good continuation.

**Comment by zuck** [comment]
Hello @PPilmeyer, thank you for your comment.

Could you please explain better what does "classic 3D rendering" mean for you?

Thank you!

**Comment by PPilmeyer** [comment]
Blinn-phong shading model or similar lighting model.

**Comment by zuck** [comment]
I see. So basically with _OpenGL utilities_ are you referring to the **L3DMaterial** class and all the stuff which binds the uniforms for the Blinn-phong shader?

**Comment by zuck** [comment]
With a92830d9 should be now possible to implement every kind of material (Blinn-phong, PBRs, etc.).

In fact, the **L3DMaterial** class is now a generic container for:
- A **shader program** (vertex, geometry, fragment shaders).
- An arbitrary number of **labeled colors**.
- An arbitrary number of **labeled textures**.
- An arbitrary number of **labeled (float) parameters**.

In this way, the _renderer_ is no more tight to a specific shading model (like **Blinn-phong**) and different types of material are just a matter of a different attribute layout (and _semantics_).

**For example, do you want to implement PBR materials?**

Instead of adding **ambient**, **diffuse** and **specular** colors with a **shininess** paramater, we can now attach a **base** color with **metalness** and **roughness** parameters, together with a total different **shader program**.

In the future I plan to also add blending attributes to materials.

**Comment by zuck** [comment]
With 37287a5, **vertex attribute names** could now be set on a per-shader basis.
